### ISSUE TITLE
Remove the "data." text in the column names.

### ISSUE THREAD

**Issue by econpotter** [ropensci/rnassqs#1]

**Comment by danielreispereira** [comment]
Came here to open exactly the same issue, so.... +1
Something along the lines of names(qsJSON) <- gsub("data.", "", names(qsJSON)) should work I think?

**Comment by econpotter** [comment]
Thanks for the push to fix this and for providing the code! The latest commit ([1473abb](https://github.com/potterzot/rnassqs/commit/1473abbf3bfb16899f810cf2423eb61fd2143656)) should do the trick.

**Comment by danielreispereira** [comment]
Many thanks! My first contribution to github, yay!
