### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by wenlong-liu** [ropensci/rnassqs#13]
Hi Nicholas,

Thanks for the time and efforts. I was trying to find an R package like this to retrieve data from NASS.  I can not wait to use this package to download data.  Great work.

Best,
Wenlong

**Comment by econpotter** [comment]
@wenlong-liu Thank you! It's wonderful to hear. I'm actually in the middle of making some clarifying updates after code review by `rOpenSci`. I will push changes later today so you may consider reinstalling from github in ~6 hours or so. Updates will not break functionality but will include better documentation and an improved vignette.
