### ISSUE TITLE
version 0.5 breaks previously working query

### ISSUE THREAD

**Issue by jdeines** [ropensci/rnassqs#17]
Hi,

I have a query that used to work in v 0.4 and return 1675 records; the same code with v 0.5 gives me an error "Request was too large..." indicating it's over the 50,000 record limit.

I discovered this because labmate was using my previous code with a freshly downloaded package - during investigated, I ran the code in question today with v0.4 and it worked, and then installed 0.5 and it didn't. So I don't believe it's due to any external changes.

Any ideas? Query is something like this (although in v0.4, I also entered my key using the 'key' argument within `nassqs` - didn't work either way here I think).

```
# test just 1 state
statesWanted <- c('IN')  #,'IL','IA','MO','SD','OH','MI','WI','MN', 'ND','NE')
nassqs_auth(key = api_key)

# param list without state
paramsNoState <- list("source_desc" = "SURVEY",
                 "agg_level_desc" = 'COUNTY',
                 "year__GE" = 2000,
                 "short_desc" = 'CORN, GRAIN - YIELD, MEASURED IN BU / ACRE')

# split up by state to avoid query limits
nasslist <- list()
for(state in statesWanted){
  params <- c(list("state_alpha" = state), paramsNoState)
  # retrieve county data by state
  nasslist[[state]] <- nassqs(params = params)
}

# convert list of data frames to 1 giant dataframe
nass.df <- do.call("rbind",nasslist)
```

**Comment by jdeines** [comment]
My labmate solved it - the argument `params` may have a different name now?

```
  nasslist[[state]] <- nassqs(params)
```

instead of

```
  nasslist[[state]] <- nassqs(params = params)
```

**Comment by econpotter** [comment]
@jdeines thanks! This was a breaking change as part of the rOpenSci review process because reviewers felt it would be easier to allow passing individual parameters _or_ as a list. Sorry for the confusion. The API is pretty well stabilized at this point so hopefully no more breaking changes will happen going forward.

As a result, in v0.5.0 the following calls are equivalent, but `nassqs(params = params)` is not:

```{r}
# As a list
nasslist[[state]] <- nassqs(params)

# Each parameter individually
nasslist[[state]] <- nassqs(source_desc = "SURVEY",
                 agg_level_desc = 'COUNTY',
                 year__GE = 2000,
                 short_desc = 'CORN, GRAIN - YIELD, MEASURED IN BU / ACRE'state_alpha = "IN")
```

**Comment by jdeines** [comment]
Cool, good to know. Thanks!
