### ISSUE TITLE
Get nassqs_param_values() for sepecific geography

### ISSUE THREAD

**Issue by sheilasaia** [ropensci/rnassqs#19]
Thank you so much for this package! I really love using it and have a suggestion for a package enhancement. I can do what I want to do in a round about way using `nassqs_record_count( )` but think it could be very helpful to be able to look up all the possible parameter values for a specific geographic region (and maybe also time period).

Maybe something like:
`nassqs_param_values(get_param = "commodity_desc", state_ansi = ..., county_ansi = ...., source_desc = ..., ....) `

I envision this call returning a list of all the commodities available for a particular county. The most general case (for the whole US) being `nassqs_param_values(get_param = "commodity_desc")`, as it is now.

**Comment by econpotter** [comment]
This is a great idea! 

Unfortunately, the API to request the values for a parameter only accepts the parameter name as an argument. The only way I can think to make this happen is to instead request the entire dataset for a set of parameters and then return a unique list of values for the specified parameter, something like:

```{r}
library(rnassqs)
nassqs_param_values <- function(param, ...) {
  d <- nassqs(...)
  unique(d[[param]]
}
nassqs_param_values(param = "commodity_desc", county_name = "YAKIMA", year = 2017)
```

I've added a [commit](https://github.com/ropensci/rnassqs/commit/f6fd91edf253e345a98fe40d9370b8e002b9342d) to do this, if you wouldn't mind installing and giving it a try:

```{r}
devtools::install("ropensci/rnassqs")
nassqs_param_values("commodity_desc", county_name = "YAKIMA", year = 2017, sector_desc = "DEMOGRAPHICS", group_desc = "EXPENSES")
```

I haven't added any checks so it will still fail if the filtered request is for more than 50,000 records.

**Comment by sheilasaia** [comment]
Thanks! I ran this:

```r
# install dev version
devtools::install_github("ropensci/rnassqs")
library(rnassqs)

# this gives 400 error and doesn't return variable
query1 <- nassqs_param_values(param = "commodity_desc", 
                              agg_level_desc = "COUNTY",
                              source_desc = "SURVEY",
                              year = "2017",
                              county_code = "53077")

# this runs without error, returns variable, but variable is empty/NULL object
query2 <- nassqs_param_values(param = "commodity_desc", 
                              agg_level_desc = "COUNTY",
                              source_desc = "SURVEY",
                              year = "2017",
                              state_ansi = "53",
                              county_ansi = "077") 
```
I think there are two things going on here. The unique values aren't printing and defining the county_code isn't working. With respect to the later, I get the same type of 400 error for query3 below. If I use the state and county ansi then I get a successful query (query4) with 4 rows.

```r
my_params3 <- list(commodity_desc = "CORN",
                   agg_level_desc = "COUNTY",
                   source_desc = "SURVEY",
                   year = "2017",
                   county_code = "53077")
my_params4 <- list(commodity_desc = "CORN",
                   agg_level_desc = "COUNTY",
                   source_desc = "SURVEY",
                   year = "2017",
                   state_ansi = "53",
                   county_ansi = "077")

# this also gives 400 error
query3 <- nassqs(my_params3)

# this runs successfully without error and gives 4 rows
query4 <- nassqs(my_params4)
```

I didn't realize the API only accepts the parameter name so that might throw a wrench in answering my original question. Let me know if I can try out any other tests. I'll try to think of another way to get around this too. Thanks again, @potterzot !

**Comment by econpotter** [comment]
Somehow I managed to introduce a bug, incorrectly test for the response, _and_ give an incorrect query... so thank you for testing this. I believe it is all fixed and in working order. For me the following works:

```{r}
devtools::install_github("ropensci/rnassqs")
rnassqs::nassqs_param_values("county_code", 
  sector_desc = "DEMOGRAPHICS", 
  group_desc = "EXPENSES", 
  year = 2012, 
  state_alpha = "WA", 
  agg_level_desc = "COUNTY")[1:2]
# Outputs:
# [1] "001" "005"
```

**Comment by sheilasaia** [comment]
Thanks so much for working on this. It's really helpful! The code above works for me. If you want a second example, this one also works.

```r
nassqs_param_values(param = "commodity_desc",
                    agg_level_desc = "COUNTY",
                    source_desc = "SURVEY",
                    year = "2017",
                    state_ansi = "53",
                    county_ansi = "077")
# gives: [1] "BARLEY" "CATTLE" "CORN"   "RENT"   "WHEAT" 
```

However, this version below is still giving a HTTP 400 error; county code isn't working when it's not the parameter of interest.

```r
nassqs_param_values(param = "commodity_desc",
                    agg_level_desc = "COUNTY",
                    source_desc = "SURVEY",
                    year = "2017",
                    county_code = "53077")
```

**Comment by econpotter** [comment]
That's great, I think it's all set then. The `county_code` parameter returns an error because it should also be in the same format as `county_ansi`, i.e. "077". I mispecified that in my original example. Thanks again for the suggestion!

**Comment by sheilasaia** [comment]
Awesome! I get it now. Thank you for implementing this! :)
