### ISSUE TITLE
Docs server

### ISSUE THREAD

**Issue by maelle** [ropensci/rnassqs#20]
:wave: here! Nice blog post!

I see you have a gh-pages pkgdown website, but you also have https://docs.ropensci.org/rnassqs/ cf https://ropensci.org/technotes/2019/06/07/ropensci-docs/

It looks good apart from the issue with your logo that's not in man/figures (see https://usethis.r-lib.org/reference/use_logo.html). Please tell me if whether you need any help with that, and if you agree, could you switch URLs to docs.ropensci.org/rnassqs? Thanks!

**Comment by econpotter** [comment]
I think that I've fixed the logo and adjusted all the links, thanks @maelle!

**Comment by maelle** [comment]
Yay, thanks! Can you please also add it to DESCRIPTION? (The URL field can contain several URLs separated with a comma)

**Comment by econpotter** [comment]
Done! I looked at some other package DESCRIPTION files for an example, hopefully did that right.

**Comment by maelle** [comment]
Cool, thanks! `desc::desc_get_urls()` return both URLs so that has to be right. :-)
