### ISSUE TITLE
USDA involvement?

### ISSUE THREAD

**Issue by rdinter** [ropensci/rnassqs#21]
Was not sure if the package has funding or endorsement through a USDA agency (my guess is USDA was not involved), but the API's [terms of service](https://quickstats.nass.usda.gov/api)  has a section on attribution:

> Attribution
> All services which utilize or access the API should display the following notice prominently within the application: "This product uses the NASS API but is not endorsed or certified by NASS." You may use the NASS name in order to identify the source of API content, subject to these rules. You may not use the NASS name to imply endorsement of any product, service, or entity (not-for-profit, commercial or otherwise).

Adding a disclaimer would help avoid any potential issues the package might face by satisfying the terms of service.

**Comment by econpotter** [comment]
@rdinter Thanks! Updated the readme and description to reflect the notice.
