### ISSUE TITLE
expand_list function error

### ISSUE THREAD

**Issue by sheilasaia** [ropensci/rnassqs#26]
Hi, I was trying to run the example given in the README vignette and am getting an error (also below).

```
params <- list(commodity_desc = "CORN",
               year__GE = 2000,
               state_alpha = c("VA", "PA"),
               statisticcat_desc = "YIELD")

df <- nassqs(params)
```

Error: "Error in expand_list(params) : could not find function "expand_list""

Am happy to provide additional information but please let me know what that would require. I'm running the version of the package from GitHub because I wanted to be able to use the `nassqs_param_values()` function.

Thank you!

**Comment by sheilasaia** [comment]
Also, if I manually load in the `expand_list()` function in helper.R script, it runs ok!

**Comment by jhavill** [comment]
I'm having the same issue, but when I load the expand_list() function manually, I encounter a new error.

**Comment by econpotter** [comment]
@jhavill can you expand on what the error message you are receiving is?

**Comment by econpotter** [comment]
Closed, this is out of date.
