### ISSUE TITLE
Add CSV/JSON/SHAPE option to functions

### ISSUE THREAD

**Issue by econpotter** [ropensci/rnassqs#3]
To make it easier for users, add

`format = c("json", "csv", "shapefile")`

to function arguments and logic to handle returning data in different formats.

**Comment by PieceMaker** [comment]
I think that's already available: https://github.com/potterzot/rnassqs/blob/master/R/nassqs.R#L37

**Comment by econpotter** [comment]
Ah yes, thanks!
