### ISSUE TITLE
Handle the HTTP 429 Too Many Requests response status code 

### ISSUE THREAD

**Issue by brandco** [ropensci/rnassqs#33]
Example:
```
library(rnassqs)
nassqs_auth("<APIKey>")

params <- list(commodity_desc = "CORN",
               year = 2012,
               agg_level_desc = "STATE",
               state_alpha = "WA",
               statisticcat_desc = "YIELD")

#BEWARE: THIS IS INTENTIONALLY MAKING TOO MANY REQUESTS AND COULD VIOLATE THE API'S TOS
for(i in 1:100) {
  response <- nassqs_GET(params)
}

# Error: lexical error: invalid char in json text.
# <html>  <head><title>429 Too Ma
# (right here) ------^
```
I believe the NASS API started throwing 429 errors around October 13th, 2022. The error is thrown from both the `nassqs_record_count` and the `nassqs` functions. 

I haven't found any documentation from NASS API on how many requests are too many.  

As a user of this package, I would like to have `nassqs_record_count` and the `nassqs` functions return the error code before trying to parse the response so that I can handle it. Maybe this could be accomplished within the `nassqs_check` function.

**Comment by pensivedog** [comment]
Also have started getting this error recently. Anyone found a solution?

**Comment by pensivedog** [comment]
I have recently started getting a similar error:

```
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html PUBLIC "-//W3C//
                     (right here) ------^
```
Is this related? Anyone have a solution?

**Comment by austinwpearce** [comment]
I am also getting the same error.
Sometimes simply reattempting to run the code results in a successful run, but success seems random.

**Comment by econpotter** [comment]
Hi Everyone, sorry for the lagging response to this. I have added a specific 429 error check. But with the lack of documentation in the API it's difficult to target specifically what's causing this with something more. If you're using the development version (`devtools::install("ropensci/rnassqs")`) and have feedback on how this error is now handled please let me know. I'll leave this issue open for now in case there are further comments/reports.

**Comment by pensivedog** [comment]
> I have recently started getting a similar error:
> 
> ```
> Error: lexical error: invalid char in json text.
>                                        <!DOCTYPE html PUBLIC "-//W3C//
>                      (right here) ------^
> ```
> 
> Is this related? Anyone have a solution?

I'm still getting this error when running the code on my server but everything runs fine locally in R Studio. Any idea what could be causing it to work in one place but not the other?

**Comment by econpotter** [comment]
@pensivedog I have improved generic HTTP error handling so hopefully you shouldn't receive any more errors like this. Will you let me know if you still do? Going to close this issue but will reopen if the problem remains / resurfaces.

**Comment by austinwpearce** [comment]
From 2025 NASS Spring Users Meeting:

> API limits to 100 calls within 5 minutes (1 call per 3 seconds)

And on a related note:

> Limit of total records (50k) may raise as they "modernize" (but nothing mentioned on how specifically Quick Stats is modernizing) 

I recently was working on some other API project and had to build something like this into a function:
```
if(status == 429) {
        # Rate limiting - get retry-after if available
        retry_after <- httr::headers(http_response)[["retry-after"]]
        wait_time <- if(!is.null(retry_after) && !is.na(as.numeric(retry_after))) {
          as.numeric(retry_after)
        } else {
          backoff_time
        }
```

Maybe I can find some time this month to explore the current state of the 429 issue.
