### ISSUE TITLE
Cannot get national level data 

### ISSUE THREAD

**Issue by dwd62** [ropensci/rnassqs#37]
I've been trying into get national level data from the NASS for livestock, poultry, and specialty animals. I've been able to get the state and county aggregated data just fine, but the national level data will show that there are zero records and when I make a request regardless there is an error
I've provided an example below from the rnassqs vignette example.

# Specify the query parameters
params <- list(
  commodity_desc = "OPERATORS",
  domain_desc = "AREA OPERATED",
  agg_level_desc = "NATIONAL",
  state_alpha = "OR",
  year = 2012
)

api_key<-"14E99758-813A-3976-B5FE-DAB3689E1E25"
Sys.setenv(NASSQS_TOKEN = api_key)
nass_set_key("14E99758-813A-3976-B5FE-DAB3689E1E25")

# Check that our record request is under the 50,000 limit
nassqs_record_count(params)

#> nassqs_record_count(params)
  #|==============================================================================================#=================================| 100%
#$count
#[1] 0

#$Value
#numeric(0)

# Get the data
d <- nassqs(params)

#Error: HTTP Failure: 400
#bad request - invalid query

Does anyone have an idea what is happening here?

**Comment by econpotter** [comment]
It looks like you are including `state_alpha = "OR"` in your parameters when querying national data. As you can imagine there is no national level data for Oregon! If I remove that I am able to successfully query 54 records.

**Comment by dwd62** [comment]
@potterzot  thanks! I didn't know that specifying the states would supersede also grabbing national level data.
