### ISSUE TITLE
Add Multiple Values for Specified Parameters

### ISSUE THREAD

**Issue by PieceMaker** [ropensci/rnassqs#5]
Issue 3 in your README todo list says "NASS API only accepts a single value for each specified parameter." However, this is incorrect if I understand what you are referring to.

As an example, suppose I want to query the 2015 corn planted acres for Adams County, Nebraska. Then I would make a GET request with the following URL:

http://quickstats.nass.usda.gov/api/api_GET/?key=access_key&commodity_desc=CORN&year=2015&state_ansi=31&county_ansi=001&short_desc=CORN%20-%20ACRES%20PLANTED

If I also wanted to know how many of these acres were irrigated, I would simply chain another `short_desc` parameter to the request, specifying the additional desired data.

http://quickstats.nass.usda.gov/api/api_GET/?key=access_key&commodity_desc=CORN&year=2015&state_ansi=31&county_ansi=001&short_desc=CORN%20-%20ACRES%20PLANTED&short_desc=CORN%2C%20IRRIGATED%20-%20ACRES%20PLANTED

Using this, it is a simple code change to allow multiple definitions of the same parameter.

Beginning at [R/nassqs.R#L43](https://github.com/potterzot/rnassqs/blob/master/R/nassqs.R#L43) the code currently reads as follows

```R
query = list("key"=key)
for (name in names(params)) { query[name] = params[name]}
query["format"] = format
```

Since `params` is a list, this can simply be changed to

```R
query = list("key"=key)
query = append(query, params)
query["format"] = format
```

Thus, the second request above could be made with the following list:

```R
params <- list(
  commodity_desc = CORN,
  year = "2015",
  state_ansi = "31",
  county_ansi = "001",
  short_desc = "CORN - ACRES PLANTED",
  short_desc = "CORN, IRRIGATED - ACRES PLANTED"
)
```

**Comment by econpotter** [comment]
Added by @PieceMaker. Thanks!
